version: '3'
services:

  #PHP Service
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: digitalocean.com/php
    container_name: app
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
    working_dir: /app
    volumes:
      - ./:/app
    depends_on:
      - db
    networks: &networks
      - default

  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    ports:
    - "3366:3306"
    expose:
      - "3306"
    environment:
      MYSQL_ROOT_PASSWORD: root

  #Nginx Service
  nginx:
    image: nginx:latest
    ports:
      - "8888:80"
      - "443:443"
    volumes:
      - ./public:/app/public
      - ./config/shop-crm.conf/:/etc/nginx/conf.d/shop-crm.conf
    networks: *networks

#  mysqldb:
#    image: mysql:latest
#    networks: *networks
#    environment:
#      MYSQL_DATABASE: shop-crm
#      MYSQL_ROOT_PASSWORD: root
##      MYSQL_USER: user
##      MYSQL_PASSWORD: root
#    ports:
#      - "3306:3306"
##    expose:
##      - '3306'
##    volumes:
##      - ./db_folders/mysql:/var/lib/mysql
##      - ./userfolder/mysql:/etc/mysql/conf.d

#Docker Networks
networks:
  default:
    name: shop
    external: true
